"""
MarketEnvironment — the simulation's observable world.

Holds sector-level state (prices, volume, volatility, excess demand) and
manages shock state for each tick.  Agents do not interact directly — they
observe the environment and respond to it.

Spec references: §2, §3, §4, §10.
"""

from __future__ import annotations

import numpy as np
from collections import deque
from dataclasses import dataclass, field

from backend.config.constants import P0, VOLATILITY_WINDOW
from backend.config.sector_config import NUM_SECTORS, LAMBDA_DEFAULTS


@dataclass
class InfluenceSignal:
    """
    Per-sector influence channel broadcast for one tick.
    Generated by active shocks or the background ambient signal.
    """
    direction: np.ndarray   # shape (NUM_SECTORS,) — signed: +1 bullish, -1 bearish, 0 neutral
    intensity: np.ndarray   # shape (NUM_SECTORS,) — 0.0–1.0 scaled signal strength


class MarketEnvironment:
    """
    Tracks all observable market state variables for the 11 GICS sectors.

    State variables (spec §2.1):
      - prices:        current sector price index (initialised at P0=100)
      - volume:        aggregate |trade magnitude| per sector this tick
      - volatility:    rolling σ of log-returns over VOLATILITY_WINDOW ticks
      - excess_demand: net buy minus sell magnitude this tick (cleared each tick)

    Also exposes the influence channel broadcast for the current tick,
    computed by the ShockProcessor (simulation/shocks.py).
    """

    def __init__(self, lambdas: list[float] | None = None) -> None:
        # Per-sector price sensitivity — higher λ means lower liquidity.
        self.lambdas: np.ndarray = np.array(
            lambdas if lambdas is not None else LAMBDA_DEFAULTS,
            dtype=float
        )
        assert len(self.lambdas) == NUM_SECTORS

        # ── Current market state ───────────────────────────────────────────────
        self.prices: np.ndarray = np.full(NUM_SECTORS, P0, dtype=float)
        self.log_prices: np.ndarray = np.log(self.prices)
        self.volume: np.ndarray = np.zeros(NUM_SECTORS, dtype=float)
        self.volatility: np.ndarray = np.zeros(NUM_SECTORS, dtype=float)
        self.excess_demand: np.ndarray = np.zeros(NUM_SECTORS, dtype=float)

        # Rolling log-return history for volatility computation.
        self._log_return_history: list[deque[float]] = [
            deque(maxlen=VOLATILITY_WINDOW) for _ in range(NUM_SECTORS)
        ]

        # ── Influence channel ──────────────────────────────────────────────────
        # Set each tick by the ShockProcessor; agents read this during activation.
        self.influence_signal: InfluenceSignal = InfluenceSignal(
            direction=np.zeros(NUM_SECTORS),
            intensity=np.zeros(NUM_SECTORS),
        )

        # ── Per-sector effective fundamental price ─────────────────────────────
        # Updated each tick by the shock processor via update_p0_effective().
        # Fundamentalist agents compute F = (p0_effective[k] - price[k]) / p0_effective[k].
        # At simulation start and in the absence of shocks this equals P0=100
        # everywhere (no belief shift).
        self.p0_effective: np.ndarray = np.full(NUM_SECTORS, P0, dtype=float)

        # ── Tick counter ───────────────────────────────────────────────────────
        self.tick: int = 0
        self.shock_active: bool = False

        # ── Price history (for chartist signal computation) ────────────────────
        # Agents hold their own signal memory; the environment keeps a short
        # recent history for the salience-bias σ reference.
        self._recent_log_returns: np.ndarray = np.zeros(
            (VOLATILITY_WINDOW, NUM_SECTORS), dtype=float
        )
        self._history_idx: int = 0

    # ── Reset ──────────────────────────────────────────────────────────────────

    def update_p0_effective(self, p0_arr: np.ndarray) -> None:
        """
        Replace the per-sector fundamental price target for the current tick.
        Called at the start of each tick by the run loop with values from the
        ShockProcessor.  Between shocks p0_arr = P0 everywhere (no change).
        """
        self.p0_effective[:] = p0_arr

    def reset(self) -> None:
        """Return to initial state for a new simulation run."""
        self.prices[:] = P0
        self.log_prices[:] = np.log(P0)
        self.volume[:] = 0.0
        self.volatility[:] = 0.0
        self.excess_demand[:] = 0.0
        self.p0_effective[:] = P0
        self.tick = 0
        self.shock_active = False
        for dq in self._log_return_history:
            dq.clear()
        self.influence_signal = InfluenceSignal(
            direction=np.zeros(NUM_SECTORS),
            intensity=np.zeros(NUM_SECTORS),
        )
        self._recent_log_returns[:] = 0.0
        self._history_idx = 0

    # ── Trade accumulation ─────────────────────────────────────────────────────

    def accumulate_trade(self, sector: int, signed_magnitude: float) -> None:
        """
        Record a trade from one agent for one sector.
        Called once per executed trade during the tick's agent loop.
        """
        self.excess_demand[sector] += signed_magnitude
        self.volume[sector] += abs(signed_magnitude)

    # ── Price update ───────────────────────────────────────────────────────────

    def apply_price_update(
        self,
        total_agent_count: int,
        aum_scale: float = 1.0,
    ) -> None:
        """
        Apply log-linear excess demand price formation at end of tick (spec §4.1):
            log p(t+1) = log p(t) + λ_k * ED(t) / (N × aum_scale)

        aum_scale — average AUM per agent in trade-magnitude units.  Pass the
        mean agent AUM to keep the formula dimensionless: when ED is expressed in
        monetary units (B USD), dividing by aum_scale converts it to a per-agent
        fraction before applying λ and 1/N.  Defaults to 1.0 for unit tests that
        pass normalised ED values directly.

        Also computes the log-return for this tick and updates volatility.
        """
        N = max(total_agent_count, 1)  # guard against zero division
        scale = N * max(aum_scale, 1.0)
        prev_log_prices = self.log_prices.copy()

        # Log-linear price update vectorised over all sectors.
        self.log_prices += self.lambdas * self.excess_demand / scale
        self.prices = np.exp(self.log_prices)

        # Compute log-returns and update rolling volatility.
        log_returns = self.log_prices - prev_log_prices
        for k in range(NUM_SECTORS):
            self._log_return_history[k].append(float(log_returns[k]))
        self._update_volatility()

        # Store in recent history array for quick sector-level σ lookups.
        self._recent_log_returns[self._history_idx] = log_returns
        self._history_idx = (self._history_idx + 1) % VOLATILITY_WINDOW

    def _update_volatility(self) -> None:
        """Recompute rolling σ of log-returns for each sector."""
        for k in range(NUM_SECTORS):
            hist = self._log_return_history[k]
            if len(hist) < 2:
                self.volatility[k] = 0.0
            else:
                self.volatility[k] = float(np.std(list(hist), ddof=1))

    # ── Tick advance ───────────────────────────────────────────────────────────

    def clear_tick_accumulators(self) -> None:
        """Reset per-tick accumulators.  Called at the START of each new tick."""
        self.excess_demand[:] = 0.0
        self.volume[:] = 0.0
        self.tick += 1

    # ── Observable market signals ──────────────────────────────────────────────

    def get_market_signals(self) -> dict[str, np.ndarray]:
        """
        Return the current market state as a dict of arrays — this is what
        agents observe each tick via the market channel.
        """
        return {
            "prices": self.prices.copy(),
            "log_prices": self.log_prices.copy(),
            "volume": self.volume.copy(),
            "volatility": self.volatility.copy(),
        }

    def get_price_history_sigma(self, sector: int) -> float:
        """
        Return the current rolling σ for a sector — used as the reference
        for salience-bias threshold detection (|Δp| > 2σ).
        """
        return float(self.volatility[sector])
